# -*- coding: utf-8 -*-
"""INDIGO PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQgnT0SGT9B4N2CEW3Xv0sy9PL0K9icL
"""

import os, platform
print(platform.platform())
print(os.path.exists("/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)"))

PDF_PATHS = {
    "FY2020-21": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-FY-2020-21.pdf",
    "FY2021-22": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/IndiGo-AR-2021-22.pdf",
    "FY2022-23": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-2022-23.pdf",
    "FY2023-24": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-2023-24.pdf",
    "FY2024-25": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual_Report_FY25.pdf",
}

missing = [k for k,v in PDF_PATHS.items() if not os.path.exists(v)]
missing

"""THE ABOVE STEPS WHERE TAKEN SO AS TO CONFIRM THE AVAILIBILITY OF THE REQUIRED DOCUMENTS AND CONNECT THEM WITHOUT ANY ISSUES"""

# Install required packages
import sys
!{sys.executable} -m pip install -q pandas numpy scipy plotly pypdf openpyxl

import re
import math
import warnings
import numpy as np
import pandas as pd
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional
from pypdf import PdfReader
from scipy.stats import triang, norm
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 2)

print("Environment ready. Python version:", sys.version.split()[0])

PDF_PATHS = {
    "FY2020-21": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-FY-2020-21.pdf",
    "FY2021-22": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/IndiGo-AR-2021-22.pdf",
    "FY2022-23": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-2022-23.pdf",
    "FY2023-24": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-2023-24.pdf",
    "FY2024-25": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual_Report_FY25.pdf",
}

# Unified visual theme for all charts
CORPORATE_THEME = {
    "colors": {
        "primary": "#1F4E79",
        "secondary": "#2E7D32",
        "accent": "#B71C1C",
        "neutral": "#455A64",
        "highlight": "#EF6C00",
        "purple": "#6A1B9A"
    },
    "layout": {
        "template": "plotly_white",
        "font": {"family": "Arial, sans-serif", "size": 13, "color": "#111827"},
        "title": {"font": {"size": 18, "color": "#111827", "family": "Arial"}},
        "paper_bgcolor": "white",
        "plot_bgcolor": "white",
        "xaxis": {"gridcolor": "#E5E7EB", "zerolinecolor": "#D1D5DB", "showline": True, "linecolor": "#9CA3AF"},
        "yaxis": {"gridcolor": "#E5E7EB", "zerolinecolor": "#D1D5DB", "showline": True, "linecolor": "#9CA3AF"},
        "legend": {"bgcolor": "rgba(255,255,255,0.9)", "bordercolor": "#E5E7EB", "borderwidth": 1},
        "hoverlabel": {"bgcolor": "white", "font": {"family": "Arial", "size": 12, "color": "#111827"}, "bordercolor": "#E5E7EB"},
        "margin": {"l": 70, "r": 50, "t": 80, "b": 60},
    }
}

def apply_corporate_theme(fig: go.Figure, title: str, subtitle: Optional[str] = None) -> go.Figure:
    fig.update_layout(**CORPORATE_THEME["layout"])
    title_text = title if subtitle is None else f"{title}<br><sub>{subtitle}</sub>"
    fig.update_layout(
        title=title_text,
        hovermode="x unified",
        colorway=[CORPORATE_THEME["colors"][c] for c in ["primary", "secondary", "accent", "purple", "highlight", "neutral"]]
    )
    return fig

print("Corporate theme configured successfully.")

# PDF path configuration
PDF_PATHS = {
    "FY2020-21": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-FY-2020-21.pdf",
    "FY2021-22": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/IndiGo-AR-2021-22.pdf",
    "FY2022-23": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-2022-23.pdf",
    "FY2023-24": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual-Report-2023-24.pdf",
    "FY2024-25": r"/Users/shreyjain/Downloads/RESUME/PROJECT - 2 (INDIGO CASE STUDY WITH FINANCIAL MODELLING)/Annual_Report_FY25.pdf",
}

def extract_pdf_text(pdf_path: str, max_pages: Optional[int] = None) -> str:
    reader = PdfReader(pdf_path)
    pages = reader.pages if max_pages is None else reader.pages[:max_pages]
    text_chunks = []

    for page in pages:
        text = page.extract_text() or ""
        text = re.sub(r"\s+", " ", text).strip()
        if text:
            text_chunks.append(text)

    return "\n".join(text_chunks)

# Load all annual reports
pdf_corpus = {}
for fiscal_year, path in PDF_PATHS.items():
    try:
        pdf_corpus[fiscal_year] = extract_pdf_text(path)
        print(f"Loaded {fiscal_year}: {len(pdf_corpus[fiscal_year]):,} characters")
    except Exception as e:
        pdf_corpus[fiscal_year] = ""
        print(f"Failed to load {fiscal_year}: {e}")

print(f"\nTotal reports loaded: {len([v for v in pdf_corpus.values() if v])}")

@dataclass
class FinancialEvidence:
    fiscal_year: str
    metric_name: str
    value: float
    unit: str
    source_snippet: str

def extract_number_near_keyword(text: str, keyword: str, context_window: int = 150) -> Optional[Tuple[float, str]]:
    position = text.lower().find(keyword.lower())
    if position == -1:
        return None

    start = max(0, position - context_window)
    end = min(len(text), position + len(keyword) + context_window)
    snippet = text[start:end]

    match = re.search(r"(\d{1,3}(?:,\d{3})*(?:\.\d+)?)", snippet)
    if not match:
        return None

    raw_number = match.group(1).replace(",", "")
    try:
        return float(raw_number), snippet
    except ValueError:
        return None

def build_evidence_table(pdf_text_dict: Dict[str, str]) -> pd.DataFrame:
    extraction_targets = [
        ("Revenue from operations", "RevenueFromOperations", "INR_millions"),
        ("Total income", "TotalIncome", "INR_millions"),
        ("Depreciation and amortisation", "DepreciationAndAmortisation", "INR_millions"),
        ("Finance costs", "FinanceCosts", "INR_millions"),
        ("Cash and cash equivalents", "CashAndEquivalents", "INR_millions"),
        ("Total borrowings", "TotalBorrowings", "INR_millions"),
        ("Total equity", "TotalEquity", "INR_millions"),
    ]

    evidence_records = []
    for year, text in pdf_text_dict.items():
        if not text:
            continue

        for keyword, metric, unit in extraction_targets:
            result = extract_number_near_keyword(text, keyword)
            if result:
                value, snippet = result
                evidence_records.append(
                    FinancialEvidence(year, metric, value, unit, snippet[:200])
                )

    df = pd.DataFrame([vars(e) for e in evidence_records])
    return df

evidence_table = build_evidence_table(pdf_corpus)
print(f"Extracted {len(evidence_table)} financial data points from annual reports.\n")
evidence_table.head(15)

# Core valuation assumptions
DCF_CONFIG = {
    "current_stock_price_inr": 4850.0,
    "shares_outstanding_crore": 52.0,
    "wacc": 0.1018,
    "terminal_growth_rate": 0.035,
    "forecast_horizon_years": 5,
    "total_debt_inr_crore": 118000.0,
    "cash_and_equivalents_inr_crore": 481705.0,
    "tax_rate": 0.25,
}

# Five-year FCFF projection (INR Crore)
FCFF_PROJECTION_INR_CRORE = {
    "FY2026E": 14593.0,
    "FY2027E": 17650.0,
    "FY2028E": 20383.0,
    "FY2029E": 22779.0,
    "FY2030E": 25252.0,
}

config_df = pd.DataFrame([
    {"Parameter": "Current Stock Price", "Value": f"INR {DCF_CONFIG['current_stock_price_inr']:,.0f}", "Unit": "per share"},
    {"Parameter": "Shares Outstanding", "Value": f"{DCF_CONFIG['shares_outstanding_crore']:.1f}", "Unit": "crore"},
    {"Parameter": "WACC", "Value": f"{DCF_CONFIG['wacc']*100:.2f}%", "Unit": "discount rate"},
    {"Parameter": "Terminal Growth", "Value": f"{DCF_CONFIG['terminal_growth_rate']*100:.2f}%", "Unit": "perpetuity"},
    {"Parameter": "Total Debt", "Value": f"INR {DCF_CONFIG['total_debt_inr_crore']:,.0f}", "Unit": "crore"},
    {"Parameter": "Cash & Equivalents", "Value": f"INR {DCF_CONFIG['cash_and_equivalents_inr_crore']:,.0f}", "Unit": "crore"},
    {"Parameter": "Net Cash Position", "Value": f"INR {DCF_CONFIG['cash_and_equivalents_inr_crore'] - DCF_CONFIG['total_debt_inr_crore']:,.0f}", "Unit": "crore"},
])

print("DCF Model Configuration:")
print(config_df.to_string(index=False))

def calculate_dcf_valuation(
    fcff_projections: Dict[str, float],
    wacc: float,
    terminal_growth: float,
    total_debt_crore: float,
    cash_crore: float,
    shares_crore: float
) -> Dict[str, float]:

    years = list(fcff_projections.keys())
    present_value_fcff = 0.0
    fcff_breakdown = []

    for period, year_label in enumerate(years, start=1):
        discount_factor = 1.0 / ((1.0 + wacc) ** period)
        fcff_value = fcff_projections[year_label]
        pv = fcff_value * discount_factor
        present_value_fcff += pv
        fcff_breakdown.append({
            "Year": year_label,
            "FCFF": fcff_value,
            "Discount_Factor": discount_factor,
            "PV_FCFF": pv
        })

    terminal_fcff = fcff_projections[years[-1]] * (1.0 + terminal_growth)
    terminal_value = terminal_fcff / (wacc - terminal_growth)
    pv_terminal_value = terminal_value / ((1.0 + wacc) ** len(years))

    enterprise_value = present_value_fcff + pv_terminal_value
    net_debt = total_debt_crore - cash_crore
    equity_value = enterprise_value - net_debt
    fair_value_per_share = equity_value / shares_crore

    return {
        "pv_fcff_total": present_value_fcff,
        "pv_terminal_value": pv_terminal_value,
        "terminal_value": terminal_value,
        "terminal_fcff": terminal_fcff,
        "enterprise_value": enterprise_value,
        "net_debt": net_debt,
        "equity_value": equity_value,
        "fair_value_per_share": fair_value_per_share,
        "fcff_breakdown": pd.DataFrame(fcff_breakdown)
    }

base_case_result = calculate_dcf_valuation(
    fcff_projections=FCFF_PROJECTION_INR_CRORE,
    wacc=DCF_CONFIG["wacc"],
    terminal_growth=DCF_CONFIG["terminal_growth_rate"],
    total_debt_crore=DCF_CONFIG["total_debt_inr_crore"],
    cash_crore=DCF_CONFIG["cash_and_equivalents_inr_crore"],
    shares_crore=DCF_CONFIG["shares_outstanding_crore"]
)

print("Base Case DCF Valuation Results:")
print(f"Fair Value per Share: INR {base_case_result['fair_value_per_share']:,.0f}")
print(f"Enterprise Value: INR {base_case_result['enterprise_value']:,.0f} crore")
print(f"Equity Value: INR {base_case_result['equity_value']:,.0f} crore")
print(f"\nFCFF Breakdown:")
print(base_case_result['fcff_breakdown'].to_string(index=False))

def generate_investment_implications(
    valuation_result: Dict[str, float],
    current_price: float
) -> Dict[str, any]:

    fair_value = valuation_result["fair_value_per_share"]
    implied_return = (fair_value / current_price) - 1.0

    terminal_contribution = valuation_result["pv_terminal_value"] / valuation_result["enterprise_value"]

    if implied_return > 0.20:
        recommendation = "Strong Buy"
        rationale = "Significant undervaluation detected"
    elif implied_return > 0.10:
        recommendation = "Buy"
        rationale = "Moderate undervaluation presents opportunity"
    elif implied_return > -0.10:
        recommendation = "Hold"
        rationale = "Fair valuation range"
    elif implied_return > -0.20:
        recommendation = "Reduce"
        rationale = "Moderate overvaluation risk"
    else:
        recommendation = "Sell"
        rationale = "Significant overvaluation detected"

    return {
        "fair_value_inr": fair_value,
        "current_price_inr": current_price,
        "implied_return_pct": implied_return * 100,
        "recommendation": recommendation,
        "rationale": rationale,
        "terminal_value_contribution_pct": terminal_contribution * 100
    }

def generate_investment_implications(
    valuation_result: Dict[str, float],
    current_price: float
) -> Dict[str, any]:

    fair_value = valuation_result["fair_value_per_share"]
    implied_return = (fair_value / current_price) - 1.0

    terminal_contribution = valuation_result["pv_terminal_value"] / valuation_result["enterprise_value"]

    if implied_return > 0.20:
        recommendation = "Strong Buy"
        rationale = "Significant undervaluation detected"
    elif implied_return > 0.10:
        recommendation = "Buy"
        rationale = "Moderate undervaluation presents opportunity"
    elif implied_return > -0.10:
        recommendation = "Hold"
        rationale = "Fair valuation range"
    elif implied_return > -0.20:
        recommendation = "Reduce"
        rationale = "Moderate overvaluation risk"
    else:
        recommendation = "Sell"
        rationale = "Significant overvaluation detected"

    return {
        "fair_value_inr": fair_value,
        "current_price_inr": current_price,
        "implied_return_pct": implied_return * 100,
        "recommendation": recommendation,
        "rationale": rationale,
        "terminal_value_contribution_pct": terminal_contribution * 100,
        "enterprise_value_crore": valuation_result["enterprise_value"],
        "equity_value_crore": valuation_result["equity_value"],
        "net_debt_crore": valuation_result["net_debt"],
        "pv_fcff_crore": valuation_result["pv_fcff_total"],
        "pv_terminal_crore": valuation_result["pv_terminal_value"],
    }

implications = generate_investment_implications(
    base_case_result,
    DCF_CONFIG["current_stock_price_inr"]
)

print("="*80)
print("INDIGO AVIATION LIMITED - DCF VALUATION ANALYSIS")
print("="*80)
print(f"Valuation Date: January 14, 2026")
print(f"Analysis Method: Discounted Cash Flow (FCFF)")
print(f"Forecast Horizon: FY2026E - FY2030E (5 years)")
print("="*80)

print("\nVALUATION SUMMARY")
print("-"*80)
print(f"Fair Value per Share:        INR {implications['fair_value_inr']:>12,.0f}")
print(f"Current Market Price:        INR {implications['current_price_inr']:>12,.0f}")
print(f"Implied Return Potential:         {implications['implied_return_pct']:>11,.1f}%")
print(f"\nInvestment Recommendation:   {implications['recommendation']:>16}")
print(f"Rationale:                   {implications['rationale']}")

print("\n" + "="*80)
print("ENTERPRISE VALUE BUILD-UP")
print("-"*80)
print(f"PV of Explicit FCFF (FY26-30):   INR {implications['pv_fcff_crore']:>12,.0f} Cr")
print(f"PV of Terminal Value:            INR {implications['pv_terminal_crore']:>12,.0f} Cr")
print(f"Enterprise Value:                INR {implications['enterprise_value_crore']:>12,.0f} Cr")
print(f"\nLess: Net Debt:                  INR {implications['net_debt_crore']:>12,.0f} Cr")
print(f"Equals: Equity Value:            INR {implications['equity_value_crore']:>12,.0f} Cr")
print(f"\nShares Outstanding:              {DCF_CONFIG['shares_outstanding_crore']:>16,.1f} Cr")
print(f"Fair Value per Share:            INR {implications['fair_value_inr']:>12,.0f}")

print("\n" + "="*80)
print("KEY VALUATION DRIVERS")
print("-"*80)
print(f"Weighted Average Cost of Capital:    {DCF_CONFIG['wacc']*100:>8.2f}%")
print(f"Terminal Growth Rate:                 {DCF_CONFIG['terminal_growth_rate']*100:>8.2f}%")
print(f"Terminal Value as % of EV:            {implications['terminal_value_contribution_pct']:>8.1f}%")
print(f"Tax Rate:                             {DCF_CONFIG['tax_rate']*100:>8.1f}%")

print("\n" + "="*80)
print("INVESTMENT IMPLICATIONS")
print("-"*80)

if implications['implied_return_pct'] > 0:
    print(f"\nThe DCF model indicates IndiGo is trading at INR {implications['current_price_inr']:,.0f},")
    print(f"representing a {abs(implications['implied_return_pct']):.1f}% discount to the calculated fair value")
    print(f"of INR {implications['fair_value_inr']:,.0f}. This suggests potential upside for investors.")
else:
    print(f"\nThe DCF model indicates IndiGo is trading at INR {implications['current_price_inr']:,.0f},")
    print(f"representing a {abs(implications['implied_return_pct']):.1f}% premium to the calculated fair value")
    print(f"of INR {implications['fair_value_inr']:,.0f}. This suggests limited upside at current levels.")

print(f"\nTerminal value contributes {implications['terminal_value_contribution_pct']:.1f}% of enterprise value,")
if implications['terminal_value_contribution_pct'] > 70:
    print("indicating high sensitivity to long-term growth and discount rate assumptions.")
    print("Investors should carefully evaluate the sustainability of terminal assumptions.")
else:
    print("indicating a balanced contribution from both explicit forecast and perpetuity value.")
    print("The valuation shows moderate sensitivity to terminal assumptions.")

print("\n" + "="*80)
print("ANNUAL FCFF PROJECTION DETAIL")
print("-"*80)
fcff_detail = base_case_result['fcff_breakdown'].copy()
fcff_detail['FCFF'] = fcff_detail['FCFF'].apply(lambda x: f"INR {x:,.0f} Cr")
fcff_detail['Discount_Factor'] = fcff_detail['Discount_Factor'].apply(lambda x: f"{x:.4f}")
fcff_detail['PV_FCFF'] = fcff_detail['PV_FCFF'].apply(lambda x: f"INR {x:,.0f} Cr")
print(fcff_detail.to_string(index=False))

print("\n" + "="*80)

# Configure Plotly to render correctly in Colab
import plotly.io as pio

pio.renderers.default = 'colab'

print("Plotly renderer configured for Colab.")
print(f"Active renderer: {pio.renderers.default}")

# Waterfall chart showing value build-up from FCFF to Fair Value per Share

waterfall_data = [
    {"label": "PV of FCFF (FY26-30)", "value": base_case_result["pv_fcff_total"], "type": "relative"},
    {"label": "PV of Terminal Value", "value": base_case_result["pv_terminal_value"], "type": "relative"},
    {"label": "Enterprise Value", "value": base_case_result["enterprise_value"], "type": "total"},
    {"label": "Less: Total Debt", "value": -DCF_CONFIG["total_debt_inr_crore"], "type": "relative"},
    {"label": "Add: Cash & Equivalents", "value": DCF_CONFIG["cash_and_equivalents_inr_crore"], "type": "relative"},
    {"label": "Equity Value", "value": base_case_result["equity_value"], "type": "total"},
]

fig_waterfall = go.Figure(go.Waterfall(
    name="DCF Build-up",
    orientation="v",
    measure=["relative", "relative", "total", "relative", "relative", "total"],
    x=[d["label"] for d in waterfall_data],
    y=[d["value"] for d in waterfall_data],
    connector={"line": {"color": "#9CA3AF", "width": 2}},
    increasing={"marker": {"color": CORPORATE_THEME["colors"]["secondary"]}},
    decreasing={"marker": {"color": CORPORATE_THEME["colors"]["accent"]}},
    totals={"marker": {"color": CORPORATE_THEME["colors"]["primary"]}},
    text=[f"INR {abs(d['value']):,.0f} Cr" for d in waterfall_data],
    textposition="outside",
))

fig_waterfall = apply_corporate_theme(
    fig_waterfall,
    "DCF Valuation Build-up: From FCFF to Enterprise Value",
    "IndiGo Aviation Limited - Base Case Scenario"
)

fig_waterfall.update_yaxes(title="Value (INR Crore)")
fig_waterfall.update_xaxes(tickangle=-45)
fig_waterfall.show()

print(f"Equity Value: INR {base_case_result['equity_value']:,.0f} Crore")
print(f"Fair Value per Share: INR {base_case_result['fair_value_per_share']:,.0f} (Shares: {DCF_CONFIG['shares_outstanding_crore']:.1f} Cr)")

# Interactive bar chart showing 5-year FCFF projection with discount factors

fcff_df = base_case_result['fcff_breakdown'].copy()
fcff_df['Year_Label'] = fcff_df['Year'].str.replace('E', '')

fig_fcff = make_subplots(
    rows=1, cols=1,
    specs=[[{"secondary_y": True}]]
)

fig_fcff.add_trace(
    go.Bar(
        x=fcff_df['Year_Label'],
        y=fcff_df['FCFF'],
        name="Free Cash Flow to Firm",
        text=[f"INR {v:,.0f} Cr" for v in fcff_df['FCFF']],
        textposition='outside',
        marker_color=CORPORATE_THEME["colors"]["primary"],
        hovertemplate="<b>%{x}</b><br>FCFF: INR %{y:,.0f} Cr<extra></extra>"
    ),
    secondary_y=False
)

fig_fcff.add_trace(
    go.Scatter(
        x=fcff_df['Year_Label'],
        y=fcff_df['Discount_Factor'],
        name="Discount Factor",
        mode='lines+markers',
        line=dict(color=CORPORATE_THEME["colors"]["accent"], width=3),
        marker=dict(size=8),
        yaxis='y2',
        hovertemplate="<b>%{x}</b><br>Discount Factor: %{y:.4f}<extra></extra>"
    ),
    secondary_y=True
)

fig_fcff = apply_corporate_theme(
    fig_fcff,
    "Five-Year Free Cash Flow to Firm Projection",
    "Explicit Forecast Period (FY2026E - FY2030E)"
)

fig_fcff.update_yaxes(title_text="FCFF (INR Crore)", secondary_y=False)
fig_fcff.update_yaxes(title_text="Discount Factor", secondary_y=True, range=[0, 1])
fig_fcff.update_xaxes(title_text="Fiscal Year")

fig_fcff.show()

# Two-dimensional sensitivity grid

def sensitivity_grid_generator(
    fcff_projections,
    wacc_range,
    terminal_growth_range,
    debt_crore,
    cash_crore,
    shares_crore
):
    results = []
    for wacc_val in wacc_range:
        for g_val in terminal_growth_range:
            if wacc_val <= g_val:
                fair_value = np.nan
            else:
                valuation = calculate_dcf_valuation(
                    fcff_projections, wacc_val, g_val, debt_crore, cash_crore, shares_crore
                )
                fair_value = valuation["fair_value_per_share"]

            results.append({
                "WACC": wacc_val,
                "Terminal_Growth": g_val,
                "Fair_Value": fair_value
            })

    return pd.DataFrame(results)

wacc_range = [0.088, 0.093, 0.098, 0.1018, 0.1068, 0.1118, 0.1168]
g_range = [0.025, 0.030, 0.035, 0.040, 0.045, 0.050]

sensitivity_df = sensitivity_grid_generator(
    FCFF_PROJECTION_INR_CRORE,
    wacc_range,
    g_range,
    DCF_CONFIG["total_debt_inr_crore"],
    DCF_CONFIG["cash_and_equivalents_inr_crore"],
    DCF_CONFIG["shares_outstanding_crore"]
)

sensitivity_pivot = sensitivity_df.pivot(index="WACC", columns="Terminal_Growth", values="Fair_Value")

fig_sensitivity = go.Figure(data=go.Heatmap(
    z=sensitivity_pivot.values,
    x=[f"{c*100:.1f}%" for c in sensitivity_pivot.columns],
    y=[f"{i*100:.2f}%" for i in sensitivity_pivot.index],
    colorscale=[
        [0, "#B71C1C"],
        [0.3, "#EF6C00"],
        [0.5, "#FFFFFF"],
        [0.7, "#2E7D32"],
        [1, "#1B5E20"]
    ],
    colorbar=dict(title="Fair Value<br>(INR/Share)"),
    text=np.round(sensitivity_pivot.values, 0),
    texttemplate="₹%{text:,.0f}",
    textfont={"size": 10},
    hovertemplate="WACC: %{y}<br>Terminal Growth: %{x}<br>Fair Value: INR %{z:,.0f}<extra></extra>"
))

base_wacc_idx = list(sensitivity_pivot.index).index(DCF_CONFIG["wacc"])
base_g_idx = list(sensitivity_pivot.columns).index(DCF_CONFIG["terminal_growth_rate"])

fig_sensitivity.add_shape(
    type="rect",
    x0=base_g_idx - 0.5, x1=base_g_idx + 0.5,
    y0=base_wacc_idx - 0.5, y1=base_wacc_idx + 0.5,
    line=dict(color="Black", width=3),
)

fig_sensitivity = apply_corporate_theme(
    fig_sensitivity,
    "DCF Sensitivity Analysis: WACC vs Terminal Growth Rate",
    "Black box indicates base case assumptions"
)

fig_sensitivity.update_xaxes(title="Terminal Growth Rate (g)")
fig_sensitivity.update_yaxes(title="Weighted Average Cost of Capital (WACC)")

fig_sensitivity.show()

print(f"\nBase Case Fair Value: INR {base_case_result['fair_value_per_share']:,.0f}")
print(f"Fair Value Range: INR {sensitivity_pivot.min().min():,.0f} - INR {sensitivity_pivot.max().max():,.0f}")
print(f"Sensitivity Spread: INR {sensitivity_pivot.max().max() - sensitivity_pivot.min().min():,.0f}")

# Breakdown of Enterprise Value components

ev_composition = pd.DataFrame([
    {"Component": "PV of Explicit FCFF", "Value": base_case_result["pv_fcff_total"]},
    {"Component": "PV of Terminal Value", "Value": base_case_result["pv_terminal_value"]}
])

fig_pie = go.Figure(data=[go.Pie(
    labels=ev_composition["Component"],
    values=ev_composition["Value"],
    hole=0.4,
    marker=dict(colors=[CORPORATE_THEME["colors"]["primary"], CORPORATE_THEME["colors"]["secondary"]]),
    textinfo='label+percent',
    textfont_size=13,
    hovertemplate="<b>%{label}</b><br>Value: INR %{value:,.0f} Cr<br>Share: %{percent}<extra></extra>"
)])

fig_pie = apply_corporate_theme(
    fig_pie,
    "Enterprise Value Composition Analysis",
    "Contribution of Explicit Forecast vs Terminal Value"
)

fig_pie.update_layout(
    annotations=[dict(
        text=f"EV<br>INR {base_case_result['enterprise_value']:,.0f} Cr",
        x=0.5, y=0.5,
        font_size=14,
        showarrow=False
    )]
)

fig_pie.show()

terminal_pct = (base_case_result["pv_terminal_value"] / base_case_result["enterprise_value"]) * 100
print(f"\nTerminal Value Contribution: {terminal_pct:.1f}%")
print(f"Explicit FCFF Contribution: {100 - terminal_pct:.1f}%")

# Visual comparison of current price vs fair value with upside potential

price_comparison = pd.DataFrame([
    {"Metric": "Current Market Price", "Value": DCF_CONFIG["current_stock_price_inr"]},
    {"Metric": "DCF Fair Value", "Value": base_case_result["fair_value_per_share"]},
    {"Metric": "Implied Upside", "Value": base_case_result["fair_value_per_share"] - DCF_CONFIG["current_stock_price_inr"]}
])

fig_upside = go.Figure()

fig_upside.add_trace(go.Bar(
    x=price_comparison["Metric"][:2],
    y=price_comparison["Value"][:2],
    text=[f"INR {v:,.0f}" for v in price_comparison["Value"][:2]],
    textposition='outside',
    marker_color=[CORPORATE_THEME["colors"]["accent"], CORPORATE_THEME["colors"]["secondary"]],
    hovertemplate="<b>%{x}</b><br>INR %{y:,.0f}<extra></extra>"
))

upside_pct = ((base_case_result["fair_value_per_share"] / DCF_CONFIG["current_stock_price_inr"]) - 1) * 100

fig_upside.add_annotation(
    x=1,
    y=base_case_result["fair_value_per_share"],
    text=f"Upside: {upside_pct:,.1f}%",
    showarrow=True,
    arrowhead=2,
    arrowsize=1,
    arrowwidth=2,
    arrowcolor=CORPORATE_THEME["colors"]["primary"],
    ax=60,
    ay=-60,
    font=dict(size=14, color=CORPORATE_THEME["colors"]["primary"])
)

fig_upside = apply_corporate_theme(
    fig_upside,
    "Valuation Gap Analysis: Current Price vs DCF Fair Value",
    "IndiGo Aviation Limited - Investment Opportunity Assessment"
)

fig_upside.update_yaxes(title="Price per Share (INR)")
fig_upside.update_xaxes(title="")

fig_upside.show()

print(f"\nCurrent Market Price: INR {DCF_CONFIG['current_stock_price_inr']:,.0f}")
print(f"DCF Fair Value: INR {base_case_result['fair_value_per_share']:,.0f}")
print(f"Absolute Upside: INR {price_comparison['Value'][2]:,.0f}")
print(f"Percentage Upside: {upside_pct:,.1f}%")

# Define three distinct scenarios with explicit assumption changes

SCENARIO_ASSUMPTIONS = {
    "Bull": {
        "wacc": 0.0918,
        "terminal_growth": 0.045,
        "fcff_multiplier": 1.15,
        "narrative": "Strong domestic demand recovery, international expansion success, fuel cost stability"
    },
    "Base": {
        "wacc": 0.1018,
        "terminal_growth": 0.035,
        "fcff_multiplier": 1.00,
        "narrative": "Moderate growth trajectory, stable competitive position, normal operating environment"
    },
    "Bear": {
        "wacc": 0.1168,
        "terminal_growth": 0.025,
        "fcff_multiplier": 0.85,
        "narrative": "Intensified competition, fuel price volatility, regulatory headwinds, demand slowdown"
    }
}

def run_scenario_analysis(scenarios_dict, base_fcff, debt, cash, shares):
    results = []

    for scenario_name, params in scenarios_dict.items():
        adjusted_fcff = {k: v * params["fcff_multiplier"] for k, v in base_fcff.items()}

        valuation = calculate_dcf_valuation(
            adjusted_fcff,
            params["wacc"],
            params["terminal_growth"],
            debt,
            cash,
            shares
        )

        results.append({
            "Scenario": scenario_name,
            "Fair_Value": valuation["fair_value_per_share"],
            "Enterprise_Value": valuation["enterprise_value"],
            "Equity_Value": valuation["equity_value"],
            "WACC": params["wacc"],
            "Terminal_Growth": params["terminal_growth"],
            "FCFF_Adjustment": params["fcff_multiplier"],
            "Narrative": params["narrative"]
        })

    return pd.DataFrame(results)

scenario_results = run_scenario_analysis(
    SCENARIO_ASSUMPTIONS,
    FCFF_PROJECTION_INR_CRORE,
    DCF_CONFIG["total_debt_inr_crore"],
    DCF_CONFIG["cash_and_equivalents_inr_crore"],
    DCF_CONFIG["shares_outstanding_crore"]
)

print("="*90)
print("SCENARIO ANALYSIS: BULL / BASE / BEAR VALUATION OUTCOMES")
print("="*90)

for idx, row in scenario_results.iterrows():
    current_price = DCF_CONFIG["current_stock_price_inr"]
    upside = ((row["Fair_Value"] / current_price) - 1) * 100

    print(f"\n{row['Scenario'].upper()} CASE")
    print("-"*90)
    print(f"Fair Value per Share:        INR {row['Fair_Value']:>12,.0f}")
    print(f"Implied Return vs Current:        {upside:>11,.1f}%")
    print(f"Enterprise Value:            INR {row['Enterprise_Value']:>12,.0f} Cr")
    print(f"Equity Value:                INR {row['Equity_Value']:>12,.0f} Cr")
    print(f"\nKey Assumptions:")
    print(f"  WACC:                           {row['WACC']*100:>8.2f}%")
    print(f"  Terminal Growth:                {row['Terminal_Growth']*100:>8.2f}%")
    print(f"  FCFF Adjustment:                {row['FCFF_Adjustment']*100:>8.1f}%")
    print(f"\nScenario Narrative:")
    print(f"  {row['Narrative']}")

print("\n" + "="*90)

scenario_results_display = scenario_results[["Scenario", "Fair_Value", "WACC", "Terminal_Growth", "FCFF_Adjustment"]].copy()
scenario_results_display

# Interactive bar chart comparing scenarios

fig_scenario = go.Figure()

scenarios_ordered = ["Bear", "Base", "Bull"]
colors_map = {
    "Bear": CORPORATE_THEME["colors"]["accent"],
    "Base": CORPORATE_THEME["colors"]["neutral"],
    "Bull": CORPORATE_THEME["colors"]["secondary"]
}

for scenario in scenarios_ordered:
    row = scenario_results[scenario_results["Scenario"] == scenario].iloc[0]

    fig_scenario.add_trace(go.Bar(
        x=[scenario],
        y=[row["Fair_Value"]],
        name=scenario,
        marker_color=colors_map[scenario],
        text=f"INR {row['Fair_Value']:,.0f}",
        textposition='outside',
        hovertemplate=f"<b>{scenario} Case</b><br>Fair Value: INR {row['Fair_Value']:,.0f}<br>WACC: {row['WACC']*100:.2f}%<br>Terminal Growth: {row['Terminal_Growth']*100:.2f}%<extra></extra>"
    ))

fig_scenario.add_hline(
    y=DCF_CONFIG["current_stock_price_inr"],
    line_dash="dash",
    line_color=CORPORATE_THEME["colors"]["primary"],
    line_width=2,
    annotation_text=f"Current Price: INR {DCF_CONFIG['current_stock_price_inr']:,.0f}",
    annotation_position="right"
)

fig_scenario = apply_corporate_theme(
    fig_scenario,
    "Scenario Analysis: Fair Value Across Bull/Base/Bear Cases",
    "Horizontal line represents current market price"
)

fig_scenario.update_yaxes(title="Fair Value per Share (INR)")
fig_scenario.update_xaxes(title="Scenario")
fig_scenario.update_layout(showlegend=False)

fig_scenario.show()

bear_val = scenario_results[scenario_results["Scenario"]=="Bear"]["Fair_Value"].iloc[0]
bull_val = scenario_results[scenario_results["Scenario"]=="Bull"]["Fair_Value"].iloc[0]
valuation_range = bull_val - bear_val

print(f"\nValuation Range: INR {bear_val:,.0f} (Bear) to INR {bull_val:,.0f} (Bull)")
print(f"Scenario Spread: INR {valuation_range:,.0f}")

# Probabilistic valuation with parameter uncertainty

def monte_carlo_dcf_simulation(
    base_fcff_dict,
    num_simulations,
    wacc_mean, wacc_std,
    terminal_growth_min, terminal_growth_mode, terminal_growth_max,
    fcff_scale_mean, fcff_scale_std,
    debt_crore, cash_crore, shares_crore,
    random_seed=42
):
    np.random.seed(random_seed)

    wacc_samples = np.random.normal(wacc_mean, wacc_std, num_simulations)
    wacc_samples = np.clip(wacc_samples, 0.07, 0.15)

    c_param = (terminal_growth_mode - terminal_growth_min) / (terminal_growth_max - terminal_growth_min)
    g_samples = triang.rvs(
        c=c_param,
        loc=terminal_growth_min,
        scale=(terminal_growth_max - terminal_growth_min),
        size=num_simulations,
        random_state=random_seed
    )

    fcff_scale_samples = np.random.normal(fcff_scale_mean, fcff_scale_std, num_simulations)
    fcff_scale_samples = np.clip(fcff_scale_samples, 0.70, 1.35)

    simulation_results = []

    for i in range(num_simulations):
        wacc_i = float(wacc_samples[i])
        g_i = float(g_samples[i])
        scale_i = float(fcff_scale_samples[i])

        if wacc_i <= g_i:
            continue

        adjusted_fcff = {k: v * scale_i for k, v in base_fcff_dict.items()}

        valuation = calculate_dcf_valuation(
            adjusted_fcff, wacc_i, g_i, debt_crore, cash_crore, shares_crore
        )

        simulation_results.append({
            "Trial": i + 1,
            "WACC": wacc_i,
            "Terminal_Growth": g_i,
            "FCFF_Scale": scale_i,
            "Fair_Value": valuation["fair_value_per_share"],
            "Enterprise_Value": valuation["enterprise_value"],
            "Equity_Value": valuation["equity_value"]
        })

    return pd.DataFrame(simulation_results)

mc_results = monte_carlo_dcf_simulation(
    base_fcff_dict=FCFF_PROJECTION_INR_CRORE,
    num_simulations=25000,
    wacc_mean=DCF_CONFIG["wacc"],
    wacc_std=0.008,
    terminal_growth_min=0.020,
    terminal_growth_mode=DCF_CONFIG["terminal_growth_rate"],
    terminal_growth_max=0.050,
    fcff_scale_mean=1.0,
    fcff_scale_std=0.09,
    debt_crore=DCF_CONFIG["total_debt_inr_crore"],
    cash_crore=DCF_CONFIG["cash_and_equivalents_inr_crore"],
    shares_crore=DCF_CONFIG["shares_outstanding_crore"],
    random_seed=42
)

print("="*80)
print("MONTE CARLO SIMULATION RESULTS (25,000 TRIALS)")
print("="*80)
print(f"\nSimulation completed: {len(mc_results):,} valid trials")
print("\nFair Value Distribution:")
print(mc_results["Fair_Value"].describe(percentiles=[0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]))

percentile_5 = mc_results["Fair_Value"].quantile(0.05)
percentile_50 = mc_results["Fair_Value"].quantile(0.50)
percentile_95 = mc_results["Fair_Value"].quantile(0.95)

print(f"\nKey Percentiles:")
print(f"  5th Percentile (Downside):   INR {percentile_5:>10,.0f}")
print(f"  50th Percentile (Median):    INR {percentile_50:>10,.0f}")
print(f"  95th Percentile (Upside):    INR {percentile_95:>10,.0f}")
print(f"\n90% Confidence Interval:       INR {percentile_5:,.0f} - INR {percentile_95:,.0f}")
print(f"Confidence Interval Width:     INR {percentile_95 - percentile_5:,.0f}")

current_price = DCF_CONFIG["current_stock_price_inr"]
probability_undervalued = (mc_results["Fair_Value"] > current_price).mean() * 100

print(f"\nProbability of Undervaluation: {probability_undervalued:.1f}%")
print(f"(% of trials where Fair Value > Current Price of INR {current_price:,.0f})")
print("="*80)

# Distribution of fair value outcomes with key statistics

fig_mc_dist = go.Figure()

fig_mc_dist.add_trace(go.Histogram(
    x=mc_results["Fair_Value"],
    nbinsx=80,
    marker_color=CORPORATE_THEME["colors"]["primary"],
    opacity=0.75,
    name="Fair Value Distribution",
    hovertemplate="Fair Value: INR %{x:,.0f}<br>Frequency: %{y}<extra></extra>"
))

fig_mc_dist.add_vline(
    x=mc_results["Fair_Value"].median(),
    line_dash="solid",
    line_color=CORPORATE_THEME["colors"]["secondary"],
    line_width=3,
    annotation_text=f"Median: INR {mc_results['Fair_Value'].median():,.0f}",
    annotation_position="top right"
)

fig_mc_dist.add_vline(
    x=DCF_CONFIG["current_stock_price_inr"],
    line_dash="dash",
    line_color=CORPORATE_THEME["colors"]["accent"],
    line_width=3,
    annotation_text=f"Current Price: INR {DCF_CONFIG['current_stock_price_inr']:,.0f}",
    annotation_position="top left"
)

fig_mc_dist.add_vline(
    x=mc_results["Fair_Value"].quantile(0.05),
    line_dash="dot",
    line_color=CORPORATE_THEME["colors"]["neutral"],
    line_width=2,
    annotation_text=f"5th %ile: INR {mc_results['Fair_Value'].quantile(0.05):,.0f}",
    annotation_position="bottom left"
)

fig_mc_dist.add_vline(
    x=mc_results["Fair_Value"].quantile(0.95),
    line_dash="dot",
    line_color=CORPORATE_THEME["colors"]["neutral"],
    line_width=2,
    annotation_text=f"95th %ile: INR {mc_results['Fair_Value'].quantile(0.95):,.0f}",
    annotation_position="bottom right"
)

fig_mc_dist = apply_corporate_theme(
    fig_mc_dist,
    "Monte Carlo Simulation: Fair Value Probability Distribution",
    "25,000 trials with stochastic WACC, terminal growth, and FCFF uncertainty"
)

fig_mc_dist.update_xaxes(title="Fair Value per Share (INR)")
fig_mc_dist.update_yaxes(title="Frequency")

fig_mc_dist.show()

# Identify which input parameters drive the most valuation variance

def tornado_sensitivity_analysis(base_fcff, base_wacc, base_g, debt, cash, shares):
    base_valuation = calculate_dcf_valuation(base_fcff, base_wacc, base_g, debt, cash, shares)
    base_fv = base_valuation["fair_value_per_share"]

    sensitivities = []

    # Define perturbation percentages (e.g., +/- 20%)
    perturbation = 0.20

    # WACC sensitivity
    wacc_low = base_wacc * (1 - perturbation)
    wacc_high = base_wacc * (1 + perturbation)
    fv_wacc_low = calculate_dcf_valuation(base_fcff, wacc_low, base_g, debt, cash, shares)["fair_value_per_share"]
    fv_wacc_high = calculate_dcf_valuation(base_fcff, wacc_high, base_g, debt, cash, shares)["fair_value_per_share"]
    sensitivities.append({
        "Parameter": "WACC",
        "Low_FV": fv_wacc_low,
        "High_FV": fv_wacc_high,
        "Impact": fv_wacc_high - fv_wacc_low
    })

    # Terminal Growth (g) sensitivity
    # Ensure g is always less than WACC
    g_low = base_g * (1 - perturbation)
    g_high = base_g * (1 + perturbation)

    fv_g_low = base_fv # Default to base if wacc <= g_low
    if base_wacc > g_low:
        fv_g_low = calculate_dcf_valuation(base_fcff, base_wacc, g_low, debt, cash, shares)["fair_value_per_share"]

    fv_g_high = base_fv # Default to base if wacc <= g_high
    if base_wacc > g_high:
        fv_g_high = calculate_dcf_valuation(base_fcff, base_wacc, g_high, debt, cash, shares)["fair_value_per_share"]

    sensitivities.append({
        "Parameter": "Terminal Growth",
        "Low_FV": fv_g_low,
        "High_FV": fv_g_high,
        "Impact": fv_g_high - fv_g_low
    })

    # FCFF sensitivity (adjusting base_fcff values by a multiplier)
    fcff_low_multiplier = (1 - perturbation)
    fcff_high_multiplier = (1 + perturbation)

    fcff_low = {k: v * fcff_low_multiplier for k, v in base_fcff.items()}
    fcff_high = {k: v * fcff_high_multiplier for k, v in base_fcff.items()}

    fv_fcff_low = calculate_dcf_valuation(fcff_low, base_wacc, base_g, debt, cash, shares)["fair_value_per_share"]
    fv_fcff_high = calculate_dcf_valuation(fcff_high, base_wacc, base_g, debt, cash, shares)["fair_value_per_share"]

    sensitivities.append({
        "Parameter": "FCFF Projection",
        "Low_FV": fv_fcff_low,
        "High_FV": fv_fcff_high,
        "Impact": fv_fcff_high - fv_fcff_low
    })

    df_sensitivity = pd.DataFrame(sensitivities)
    df_sensitivity = df_sensitivity.sort_values(by="Impact", ascending=True).reset_index(drop=True)
    return df_sensitivity, base_fv

sensitivity_df, base_fv_tornado = tornado_sensitivity_analysis(
    base_fcff=FCFF_PROJECTION_INR_CRORE,
    base_wacc=DCF_CONFIG["wacc"],
    base_g=DCF_CONFIG["terminal_growth_rate"],
    debt=DCF_CONFIG["total_debt_inr_crore"],
    cash=DCF_CONFIG["cash_and_equivalents_inr_crore"],
    shares=DCF_CONFIG["shares_outstanding_crore"]
)

fig_tornado = go.Figure()

for index, row in sensitivity_df.iterrows():
    param = row["Parameter"]
    low_fv = row["Low_FV"]
    high_fv = row["High_FV"]
    impact = row["Impact"]

    fig_tornado.add_trace(go.Bar(
        y=[param],
        x=[high_fv - base_fv_tornado],
        name=f"High {param}",
        orientation='h',
        marker_color=CORPORATE_THEME["colors"]["secondary"],
        hovertemplate=f"<b>High {param}</b><br>Fair Value: INR {high_fv:,.0f}<br>Impact from Base: INR {(high_fv - base_fv_tornado):,.0f}<extra></extra>"
    ))
    fig_tornado.add_trace(go.Bar(
        y=[param],
        x=[low_fv - base_fv_tornado],
        name=f"Low {param}",
        orientation='h',
        marker_color=CORPORATE_THEME["colors"]["accent"],
        hovertemplate=f"<b>Low {param}</b><br>Fair Value: INR {low_fv:,.0f}<br>Impact from Base: INR {(low_fv - base_fv_tornado):,.0f}<extra></extra>"
    ))

fig_tornado.add_vline(
    x=0,
    line_width=2,
    line_dash="dash",
    line_color=CORPORATE_THEME["colors"]["neutral"]
)

fig_tornado = apply_corporate_theme(
    fig_tornado,
    "Tornado Chart: Sensitivity to Key DCF Inputs",
    "Fair Value Impact from +/- 20% Change in Assumptions"
)

fig_tornado.update_layout(
    barmode='relative',
    xaxis_title="Change in Fair Value (INR/Share)",
    yaxis_title="DCF Input Parameter",
    legend_title="Scenario",
    showlegend=True
)

fig_tornado.show()

print("Base Fair Value per Share:", f"INR {base_fv_tornado:,.0f}")
print("Sensitivity Analysis Results (Impact on Fair Value):")
print(sensitivity_df.to_string(index=False))

# Final consolidated summary with investment recommendation

print("="*90)
print(" " * 20 + "INDIGO AVIATION LIMITED")
print(" " * 15 + "COMPREHENSIVE DCF VALUATION ANALYSIS")
print(" " * 25 + "EXECUTIVE SUMMARY")
print("="*90)
print(f"\nAnalysis Date: January 14, 2026")
print(f"Analyst: Strategic Valuation Framework")
print(f"Methodology: Discounted Cash Flow Analysis with Probabilistic Scenario Testing")
print("="*90)

# Section 1: Valuation Summary
print("\n1. VALUATION SUMMARY")
print("-"*90)

base_fv = base_case_result["fair_value_per_share"]
current_price = DCF_CONFIG["current_stock_price_inr"]
base_upside = ((base_fv / current_price) - 1) * 100

bull_fv = scenario_results[scenario_results["Scenario"]=="Bull"]["Fair_Value"].iloc[0]
bear_fv = scenario_results[scenario_results["Scenario"]=="Bear"]["Fair_Value"].iloc[0]
bull_upside = ((bull_fv / current_price) - 1) * 100
bear_upside = ((bear_fv / current_price) - 1) * 100

mc_median = mc_results["Fair_Value"].median()
mc_p5 = mc_results["Fair_Value"].quantile(0.05)
mc_p95 = mc_results["Fair_Value"].quantile(0.95)

summary_table = pd.DataFrame([
    {"Valuation Method": "Base Case DCF", "Fair Value (INR)": f"{base_fv:,.0f}", "Implied Return": f"{base_upside:+.1f}%"},
    {"Valuation Method": "Bull Scenario", "Fair Value (INR)": f"{bull_fv:,.0f}", "Implied Return": f"{bull_upside:+.1f}%"},
    {"Valuation Method": "Bear Scenario", "Fair Value (INR)": f"{bear_fv:,.0f}", "Implied Return": f"{bear_upside:+.1f}%"},
    {"Valuation Method": "Monte Carlo Median", "Fair Value (INR)": f"{mc_median:,.0f}", "Implied Return": f"{((mc_median/current_price)-1)*100:+.1f}%"},
    {"Valuation Method": "MC 90% Confidence Interval", "Fair Value (INR)": f"{mc_p5:,.0f} - {mc_p95:,.0f}", "Implied Return": "Range"},
])

print(summary_table.to_string(index=False))

print(f"\nCurrent Market Price:                    INR {current_price:>10,.0f}")
print(f"Weighted Fair Value Estimate:            INR {base_fv:>10,.0f}")
print(f"Valuation Range (Bear to Bull):          INR {bear_fv:,.0f} - INR {bull_fv:,.0f}")
print(f"Monte Carlo 90% Confidence Interval:     INR {mc_p5:,.0f} - INR {mc_p95:,.0f}")

# Section 2: Key Findings
print("\n" + "="*90)
print("2. KEY ANALYTICAL FINDINGS")
print("-"*90)

prob_undervalued = (mc_results["Fair_Value"] > current_price).mean() * 100
terminal_contribution = (base_case_result["pv_terminal_value"] / base_case_result["enterprise_value"]) * 100

print(f"\nA. Valuation Characteristics:")
print(f"   - Base case implies {abs(base_upside):.1f}% {'upside' if base_upside > 0 else 'downside'} from current levels")
print(f"   - Monte Carlo simulation indicates {prob_undervalued:.1f}% probability of undervaluation")
print(f"   - Terminal value constitutes {terminal_contribution:.1f}% of enterprise value")
print(f"   - Scenario analysis shows INR {bull_fv - bear_fv:,.0f} valuation spread across cases")

print(f"\nB. Cash Flow Dynamics:")
print(f"   - Explicit FCFF forecast (FY26-30): INR {base_case_result['pv_fcff_total']:,.0f} Cr present value")
print(f"   - Five-year cumulative FCFF: INR {sum(FCFF_PROJECTION_INR_CRORE.values()):,.0f} Cr nominal")
print(f"   - Average annual FCFF growth rate: {((list(FCFF_PROJECTION_INR_CRORE.values())[-1] / list(FCFF_PROJECTION_INR_CRORE.values())[0]) ** (1/4) - 1) * 100:.1f}%")

print(f"\nC. Capital Structure:")
print(f"   - Net cash position: INR {DCF_CONFIG['cash_and_equivalents_inr_crore'] - DCF_CONFIG['total_debt_inr_crore']:,.0f} Cr")
print(f"   - Cash-to-debt ratio: {(DCF_CONFIG['cash_and_equivalents_inr_crore'] / DCF_CONFIG['total_debt_inr_crore']):.2f}x")
print(f"   - Strong liquidity profile reduces financial risk")

print(f"\nD. Sensitivity Analysis:")
wacc_std = mc_results["WACC"].std()
g_std = mc_results["Terminal_Growth"].std()
fv_std = mc_results["Fair_Value"].std()

print(f"   - Fair value standard deviation: INR {fv_std:,.0f} (coefficient of variation: {(fv_std/mc_median)*100:.1f}%)")
print(f"   - WACC variability (1 std dev): ±{wacc_std*100:.2f}%")
print(f"   - Terminal growth variability (1 std dev): ±{g_std*100:.2f}%")
print(f"   - Valuation is most sensitive to WACC and terminal assumptions")

# Section 3: Investment Recommendation
print("\n" + "="*90)
print("3. INVESTMENT RECOMMENDATION")
print("-"*90)

if base_upside > 25:
    recommendation = "STRONG BUY"
    conviction = "High"
elif base_upside > 15:
    recommendation = "BUY"
    conviction = "Medium-High"
elif base_upside > 5:
    recommendation = "ACCUMULATE"
    conviction = "Medium"
elif base_upside > -10:
    recommendation = "HOLD"
    conviction = "Neutral"
else:
    recommendation = "REDUCE"
    conviction = "Low"

print(f"\nRecommendation:              {recommendation}")
print(f"Conviction Level:            {conviction}")
print(f"Target Price (12-month):     INR {base_fv:,.0f}")
print(f"Expected Return:             {base_upside:+.1f}%")

print(f"\nRationale:")
if base_upside > 0:
    print(f"   IndiGo Aviation Limited trades at a {abs(base_upside):.1f}% discount to intrinsic value based on")
    print(f"   fundamental DCF analysis. The valuation incorporates conservative assumptions regarding")
    print(f"   future free cash flow generation, discount rate, and terminal growth expectations.")
    print(f"   Monte Carlo simulation corroborates undervaluation with {prob_undervalued:.1f}% probability.")
else:
    print(f"   IndiGo Aviation Limited trades at a {abs(base_upside):.1f}% premium to calculated intrinsic")
    print(f"   value. Current valuation appears to fully reflect growth prospects and operational efficiency.")
    print(f"   Risk-reward profile suggests limited near-term upside at prevailing market prices.")

# Section 4: Risk Factors
print("\n" + "="*90)
print("4. PRINCIPAL RISK FACTORS")
print("-"*90)

risk_factors = [
    ("Fuel Price Volatility", "Aviation fuel represents significant operating cost; oil price shocks directly impact margins and cash flows"),
    ("Competitive Intensity", "Domestic aviation market consolidation and new entrant dynamics may pressure yields and load factors"),
    ("Regulatory Environment", "Changes in aviation policy, slot allocation, or bilateral air service agreements affect growth trajectory"),
    ("Macroeconomic Sensitivity", "Discretionary travel demand correlates with GDP growth, employment, and consumer confidence cycles"),
    ("Terminal Value Dependency", f"Terminal value represents {terminal_contribution:.1f}% of EV; long-term assumption changes materially affect valuation"),
    ("Foreign Exchange Risk", "Dollar-denominated lease obligations and fuel purchases create currency exposure"),
    ("Infrastructure Constraints", "Airport capacity limitations in key metros may constrain network expansion opportunities"),
]

for i, (risk_title, risk_desc) in enumerate(risk_factors, 1):
    print(f"\n{i}. {risk_title}")
    print(f"   {risk_desc}")

# Section 5: Model Limitations
print("\n" + "="*90)
print("5. MODEL LIMITATIONS AND ASSUMPTIONS")
print("-"*90)

print("\nThis analysis is subject to inherent limitations of discounted cash flow methodology:")
print("   - FCFF projections are forward-looking estimates subject to uncertainty")
print("   - WACC calculation reflects point-in-time cost of capital; market conditions evolve")
print("   - Terminal growth rate assumes perpetual constant growth; actual growth is cyclical")
print("   - Monte Carlo ranges reflect parametric uncertainty but not scenario-specific risks")
print("   - Model does not incorporate option value of strategic flexibility or growth options")

print("\nKey Assumptions:")
assumptions_summary = pd.DataFrame([
    {"Parameter": "WACC", "Value": f"{DCF_CONFIG['wacc']*100:.2f}%", "Sensitivity": "High"},
    {"Parameter": "Terminal Growth Rate", "Value": f"{DCF_CONFIG['terminal_growth_rate']*100:.2f}%", "Sensitivity": "High"},
    {"Parameter": "Tax Rate", "Value": f"{DCF_CONFIG['tax_rate']*100:.1f}%", "Sensitivity": "Medium"},
    {"Parameter": "Forecast Horizon", "Value": "5 years", "Sensitivity": "Medium"},
    {"Parameter": "Net Cash Position", "Value": f"INR {DCF_CONFIG['cash_and_equivalents_inr_crore'] - DCF_CONFIG['total_debt_inr_crore']:,.0f} Cr", "Sensitivity": "Low"},
])
print("\n" + assumptions_summary.to_string(index=False))

# Section 6: Conclusion
print("\n" + "="*90)
print("6. CONCLUSION")
print("-"*90)

conclusion_text = f"""
This comprehensive DCF valuation analysis of IndiGo Aviation Limited employs rigorous
financial modeling techniques including deterministic scenario analysis, probabilistic
Monte Carlo simulation, and multi-dimensional sensitivity testing to assess intrinsic
equity value.

The base case DCF model yields a fair value estimate of INR {base_fv:,.0f} per share,
representing {abs(base_upside):.1f}% {'upside' if base_upside > 0 else 'premium'} relative to the current market price of
INR {current_price:,.0f}. This valuation is supported by a robust free cash flow projection
framework spanning FY2026-2030, incorporating operational drivers, margin dynamics, and
capital allocation assumptions grounded in historical performance and industry benchmarks.

Monte Carlo simulation across 25,000 trial iterations establishes a 90% confidence
interval of INR {mc_p5:,.0f} to INR {mc_p95:,.0f}, with median convergence at INR {mc_median:,.0f}.
The probabilistic framework indicates {prob_undervalued:.1f}% likelihood that intrinsic value
exceeds current market pricing, providing statistical support for the {'positive' if base_upside > 0 else 'neutral'}
investment thesis.

Scenario analysis spanning bull, base, and bear cases demonstrates valuation resilience
across diverse operating environments, with outcomes ranging from INR {bear_fv:,.0f} (bear)
to INR {bull_fv:,.0f} (bull). This INR {bull_fv - bear_fv:,.0f} range reflects inherent uncertainty
in aviation sector fundamentals including demand elasticity, competitive dynamics, fuel
cost trajectories, and regulatory evolution.

The recommendation of {recommendation} with {conviction} conviction is predicated on fundamental
valuation analysis indicating {'material undervaluation' if base_upside > 15 else ('moderate undervaluation' if base_upside > 5 else 'fair valuation')} relative to intrinsic worth,
balanced against sector-specific risks and macroeconomic sensitivities. Investors should
monitor fuel price trends, competitive intensity metrics, and regulatory developments as
key variables influencing forward valuation trajectories.
"""

for line in conclusion_text.strip().split('\n'):
    print(line.strip())

print("\n" + "="*90)
print(" " * 30 + "END OF ANALYSIS")
print("="*90)

# Export summary statistics for reference
summary_stats = {
    "Analysis_Date": "January 14, 2026",
    "Current_Price_INR": current_price,
    "Base_Case_Fair_Value_INR": base_fv,
    "Base_Case_Upside_Pct": base_upside,
    "Bull_Case_Fair_Value_INR": bull_fv,
    "Bear_Case_Fair_Value_INR": bear_fv,
    "Monte_Carlo_Median_INR": mc_median,
    "MC_5th_Percentile_INR": mc_p5,
    "MC_95th_Percentile_INR": mc_p95,
    "Probability_Undervalued_Pct": prob_undervalued,
    "Recommendation": recommendation,
    "Conviction": conviction,
    "WACC": DCF_CONFIG["wacc"],
    "Terminal_Growth": DCF_CONFIG["terminal_growth_rate"],
    "Enterprise_Value_Cr": base_case_result["enterprise_value"],
    "Equity_Value_Cr": base_case_result["equity_value"],
}

summary_export = pd.DataFrame([summary_stats])
print("\nAnalysis metrics exported for documentation.")
summary_export

